### ISSUE TITLE
Rename SPRING.md to README.md

### ISSUE THREAD

**Issue by achaval-tomas** [MauricioLlugdar/WhySpring#3]
This way, visitors can directly get to reading! 💪

**Comment by tomimara52** [comment]
i think it is a very good idea, since the repo itself is called WhySpring and it only contains de md file

**Comment by achaval-tomas** [comment]
Maybe @MauricioLlugdar could open a discussion space from the repo's settings to talk about these things before opening issues! 🚀

**Comment by tomimara52** [comment]
maaan 🙌🏼, that would be really cool @MauricioLlugdar 💁🏼‍♀️

**Comment by MauricioLlugdar** [comment]
You are right @achaval-tomas, you are really helping with these repo. Maybe when I die, giving it to you could be a great gesture of me, as a good samaritan and a marvelous person that I am
