### ISSUE TITLE
SpringInitialzr.png typo

### ISSUE THREAD

**Issue by tpeyronel** [MauricioLlugdar/WhySpring#4]
SpringInitialzr.png is correctly named, there is actually nothing to fix.

**Comment by MauricioLlugdar** [comment]
No it should not, look for more information in  https://www.geeksforgeeks.org/spring-initializr/  Please be welcome to try it again, but next time really try it
![Captura](https://github.com/MauricioLlugdar/WhySpring/assets/67161167/71ad04b4-1426-44d7-8e15-d80da361f75e)
You are changing your issues Mercenary

**Comment by tomimara52** [comment]
you shouldnt create issues asserting things that are ok

**Comment by tpeyronel** [comment]
I'm sorry @tomimara52, i don't know which pull request you are talking about. Could you please enlighten me? Thanks.

**Comment by tomimara52** [comment]
haha @tpeyronel, what exactly are u talking about?

**Comment by tpeyronel** [comment]
Erm, i don't know, it seems that I got confused.
